# Generated by Django 4.2.3 on 2023-09-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=400)),
                ('publisher', models.CharField(max_length=200)),
                ('img_urls', models.CharField(max_length=400)),
            ],
        ),
    ]
