# Generated by Django 4.2.3 on 2023-09-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='img_urls',
            new_name='img_url1',
        ),
        migrations.AddField(
            model_name='books',
            name='img_url2',
            field=models.CharField(default='null', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='img_url3',
            field=models.CharField(default='null', max_length=400),
            preserve_default=False,
        ),
    ]
