# Generated by Django 4.2.3 on 2023-09-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.CharField(default='200', max_length=10),
            preserve_default=False,
        ),
    ]
